### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MrSaints** [MrSaints/www-jekyll.fyianlai.com#1]
- [x] About page
- [x] Contact us page
- [x] Improve paginator (not easily recognisable ATM)
- [x] Add links to other articles (within a page)
- [x] Disqus
- [x] Modernizr
- [x] Meta (social media)

**Comment by MrSaints** [comment]
All completed.
